spring:
  # 缓存数据库 redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # Redis数据库索引（默认为0）
    database: 6
    # 连接超时时间（毫秒）
    timeout: 3000ms
    # Lettuce配置
    lettuce:
      # 连接池
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
